### PR TITLE
404 redirect fix

### PR DESCRIPTION
**Pull request by mat-px**
I am not sure what the cache file is or why it was added.

Also not sure if this will fix it or not because when I tested it locally it did not work, but stackoverflow claims it does.
https://stackoverflow.com/questions/45672351/firebase-hosting-create-a-404-page

### CODE REVIEW

**Comment by joe-studer-18** [comment]
Looks like you may need to [sync this branch with main](https://intellipaat.com/community/14332/how-to-keep-a-git-branch-in-sync-with-master). There's a couple ways to run the local firebase simulator, and each one is a bit different (which is super annoying). Maybe try running 
```
firebase emulators:start
```
then testing it.

**Review by joe-studer-18 — COMMENTED** [review]
Previous comments are the review :)

**Comment by mat-px** [comment]
I decided to read the firebase documentation and I really overlooked it, all I had to do was have the right name for the 404 page and it would automatically redirect.

**Review by joe-studer-18 — APPROVED** [review]
Ahh neat, that'll do then.

**Pull request merged**
