### PR TITLE
removed terms/policy, shifted bottom footer left

### PR DESCRIPTION
**Pull request by ldhtnp**
I removed the privacy policy and terms of use from the footer. I also shifted the "Developed by Beta Alpha of Kappa Alpha and hosted on Github" to the left.

### CODE REVIEW

**Review by joe-studer-18 — COMMENTED** [review]
Before this gets merged we’ll want to apply the changes to all the pages, not just the index. It looks good on desktop, but looks like it wraps to a second line on mobile now. I’m on my iPad so not sure what the reasoning is, but may be worth shrinking the text size a bit on mobile?

**Comment by ldhtnp** [comment]
> Before this gets merged we’ll want to apply the changes to all the pages, not just the index. It looks good on desktop, but looks like it wraps to a second line on mobile now. I’m on my iPad so not sure what the reasoning is, but may be worth shrinking the text size a bit on mobile?

@joe-studer-18 Privacy policy and terms of use should be removed for all pages now. The text shouldn't wrap on any mobile device now as well

**Comment by joe-studer-18** [comment]
Looks like devel was overwritten, would you mind pushing again?

**Comment by ldhtnp** [comment]
@joe-studer-18 done

**Review by joe-studer-18 — APPROVED** [review]

**Comment by joe-studer-18** [comment]
This is good to merge btw :)

**Pull request merged**
