### PR TITLE
Jstuder/cleanup

### PR DESCRIPTION
**Pull request by joe-studer-18**
Cleaning up small issues w/ formatting on contact us and about pages.

### CODE REVIEW

**Comment by noahklein00** [comment]
When first loading into the ABOUT US page, the top little social media banner doesn't load in. It loads once you scroll on the page, but it doesn't show it at first like the other pages do.

**Comment by noahklein00** [comment]
Also could you add a little bit of spacing in between the photo and the text paragraph on the AWARDS main page. You can see especially in the line that ends with "is" that the photo almost goes over the text. The ABOUT US page has a little bit of spacing if you could just copy that.

**Comment by joe-studer-18** [comment]
Fixed 'em both - good catches! Tbh I think the awards page needs an entire revamp, maybe even in to just one page using flex grid boxes. Right now it's a lot of dead space.

**Review by jaredwhanisch — APPROVED** [review]
LGTM!

**Pull request merged**
