### PR TITLE
Finalized styles for all mobile pages.

### LINKED ISSUE #68: Mobile Formatting
The mobile version of the website is just a little off -> some pages need centering of text/images/headers/etc. Lets go through all the pages & make sure they look good in mobile, without changing how they look on desktop.

### PR DESCRIPTION
**Pull request by jaredwhanisch**
This should take care of all of the mobile pages and subsequent subpages, if you see anything that looks wack, just let me know and I'll see what I can do to make it look better. Thanks!

Closes #68

### CODE REVIEW

**Comment by joe-studer-18** [comment]
Can we center the icons & text on the homepage like the other pages?

**Comment by joe-studer-18** [comment]
plz ignore all the bs w/ weird commits to this branch...I goofed. It should be back to its normal state :)

**Comment by jaredwhanisch** [comment]
@joe-studer-18 Sorry it took so long to do this, I had some stuff come up with family. I ended up only centering the values section text and images, I was looking at centering the about section on the homepage, but it just didn't look very good to me centered. So I left it. If you'd rather me go ahead and center it anyway, just let me know, no biggie.

**Comment by joe-studer-18** [comment]
I'll have to return your apology, I didn't have things come up, I just get bad about procrastinating some times. This looks great to me, and I hope everything is good with your family.

**Review by joe-studer-18 — APPROVED** [review]

**Pull request merged**
