### PR TITLE
Jstuder/mobilenav

### PR DESCRIPTION
**Pull request by joe-studer-18**
Here's a rough draft of a mobile navbar. It's only on about.html as of now, but I was hoping one or both of you could take a look at it and give me some feedback before I move it to all the pages. It makes the html for each page quite a bit bigger :( but it looks pretty good & works. 

Closing #69

### CODE REVIEW

**Comment by noahklein00** [comment]
It looks like you cannot re-open the drop down menu if you are not on the about.html page. Say I was on About -> BA of KA Greek Life, I could not open the drop down menu to go to another about subpage without first going back to About.

It seems as though the z-axis on the about.html class="page_info about-nav-background" div is higher than the the secondary drop down menu, so the text on the header is appearing above the secondary drop down.

Finally, it would be nice if there was a little triangle/arrow thing to indicate that there was a secondary drop down menu because it took me a minute to realize that that's where it was.

**Comment by joe-studer-18** [comment]
Yeah I haven't added it to "BA of KA Greek Life" or any of the other subpages yet, so that's intended behavior. I'd noticed the issue w/ z-axis but wanted to see if it was repro'd first yet, so that's good to know. 

Definitely a good call on the arrow, I hadn't even thought of that. I'll add that as well before I push again

**Comment by joe-studer-18** [comment]
@noahklein00 can you check it again? Still only on the about.html page but the z-index & caret stuff should be better now. I'm working on css for the sub-nav buttons now, but after that should hopefully be g2g on pushing to all pages.

**Comment by joe-studer-18** [comment]
Wait I take it back. Z-index issue is still there

**Comment by joe-studer-18** [comment]
Ok for real this time it should work.

**Review by jaredwhanisch — APPROVED** [review]
I think it looks great! I thought originally this dropdown was going to go on the grey bar section where the links live on the desktop version, but think putting them in the main nav dropdown is a way better way to do it.

**Pull request merged**
