### PR TITLE
reduced resolution of photo by 50%

### PR DESCRIPTION
**Pull request by noahklein00**
I think this should solve almost all of the slowdown problems with mobile. I don't know how to test that myself so ya here's what it is.

### CODE REVIEW

**Comment by joe-studer-18** [comment]
You can test by running

```
firebase deploy
```

Then after it's updated, visit this [site](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmst-ka.firebaseapp.com%2F&hl=en&tab=mobile)

**Comment by noahklein00** [comment]
It reduced a large chunk of it, but it only changed the score from 71 to 72 wahoo... A large suggestion it has is formatting the images in "next-gen formats" but none of the ones they list are widely supported (JPEG 2000, JPEG XR, WebP).

**Comment by joe-studer-18** [comment]
Can you look up what a good mobile score is? Like run that tool on something that should be pretty well optimized, but still has a decent size landing page. Maybe mst.edu or similar.

**Comment by noahklein00** [comment]
Screenshot (43)
Honestly idk why I expected anything better lmao

**Comment by noahklein00** [comment]
Pornhub scores a 78 for mobile and 97 for desktop!

**Comment by joe-studer-18** [comment]
Wow outstanding job S&T. I guess lets shoot for something in the high-70s then? Maybe work on the render blocking resources & main thread work? Its a very "chip away at it" kinda thing.

**Comment by joe-studer-18** [comment]
So it's probably also worth noting that the current website scores an 11 on mobile & a 61 on desktop....I think we're good as is.

**Review by joe-studer-18 — APPROVED** [review]

**Pull request merged**
